---
title: "Tidying Lebron James Shot Data"
output: github_document
---

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Loading data into R

```{r}
lbj_data <- read_csv("https://raw.githubusercontent.com/UBC-MDS/DSCI-522-Jes-Alex/master/data/shot_logs_raw.csv?token=Ao9QkTPZ0S2NSZI8bIRGzjLZHbaycrCbks5b93bjwA%3D%3D")

View(lbj_data)

```

## Filtering raw data for Lebron James's shots and selecting our classifier columns

```{r}
# filtering for all shots by Lebron James
# dropping the one row with negative touch time
# Assuming NA in shot_clock is a buzzer shot, and replacing NAs with zeros

lbj_data_clean <- lbj_data %>% 
  filter(player_name == "lebron james",
         TOUCH_TIME >= 0) %>% 
  mutate(SHOT_CLOCK = replace_na(SHOT_CLOCK, 0)) %>% 
  select(SHOT_CLOCK, SHOT_NUMBER, SHOT_DIST, SHOT_RESULT, TOUCH_TIME, PERIOD, PTS_TYPE, DRIBBLES, CLOSE_DEF_DIST)

  
write.csv(lbj_data_clean, "lbj_shots_tidy.csv")

```

```{r}
data_check <- read_csv("data/tidy_data_lebron_james.csv")

View(data_check)
```

